### PR TITLE
Adjustment of Config.Toml & Docker Config To Faciitate Bootnode Discovery

### PR DESCRIPTION
**Pull request by dbkbali**
These changes allow for bootnode discovery on the shyft testnet. Docker changes were made to expose necessary ports and for persistent pg data through a docker volume. @priom please review

### CODE REVIEW

**Comment by dbkbali** [comment]
There is no documentation as connection to a bootnode is automatic, via the config included in the config.toml - via the hardcoded enode addresses which is picked up in the startup script when the geth node is started.

**Comment by GregTheGreek** [comment]
I see... I believe we will want to have the enode optional @priom

**Comment by priom** [comment]
@GregTheGreek but we need to it to be able to connect to peers, right?

**Comment by GregTheGreek** [comment]
@priom should be able to connect to any enode of your hoice ?

**Comment by priom** [comment]
@GregTheGreek @dbkbali @larry-shyft We have to pass the boot nodes directly in the genesis block. Take a look at Robsten's genesis block https://github.com/paritytech/parity-ethereum/blob/584a76ab7009e0b608d6c3d454c2a992c7d78e32/ethcore/res/ethereum/ropsten.json

**Pull request merged**
