### PR TITLE
ShyftGeth & PG Dockerized With Persistent DB Storage

### PR DESCRIPTION
**Pull request by dbkbali**
This is an interim commit which allows ShyftGeth and PG to be launched in docker containers. Merge is being requested into staging so that we can also complete automated builds of these docker images within DockerHub. Docker images are in the process of being completed for the BlockExplorer Api and UI.

### CODE REVIEW

**Comment by GregTheGreek** [comment]
@dbkbali There is a conflict

**Comment by priom** [comment]
@dbkbali can u merge the conflict and update the PR

**Comment by dbkbali** [comment]
Please could each of you try on your machines. NB: Shyft Geth Docker Image is 5 GB - so make sure you have space. Also there appear to still be some bugs in the ShyftBlockExplorerApi when getAllAccounts is called from the UI

**Comment by GregTheGreek** [comment]
Mining: good
3000: good (but no content)
8001: Error, cannot find webpage

**Comment by dbkbali** [comment]
@GregTheGreek 8001 is the expected result as this is the api.
on 3000 you should be seeing the blockexplorer ui - as long as the genesis.json has been loaded and the DAG's have all generated after mining has started (prior to DAG completion you will see the UI with no accounts). 

If you want to restart fresh you need to delete the pg-data folder (persisted db) and the $HOME folder with the blockchain.

Could you do a `docker container ls` and make sure you have 4 containers running. As 2 of the containers are dependent on PG and there is a timeout of 30 seconds - for slower machines I may need to increase the timeout. If not all containers are running let me know which ones.

screen shot 2018-08-05 at 8 56 12 am

**Comment by larry-shyft** [comment]
Hi I am running shyftDockerize branch, and 3/4 containers are running (block ui, shyft geth, pg)
Is it expected that running "docker logs go-empyrean_shyft_block_api_1: shows below error?

github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/crypto/secp256k1
# github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/crypto/secp256k1
vendor/github.com/ShyftNetwork/go-empyrean/crypto/secp256k1/curve.go:43:44: fatal error: libsecp256k1/include/secp256k1.h: No such file or directory
 #include "libsecp256k1/include/secp256k1.h"
                                            ^
compilation terminated.

**Comment by GregTheGreek** [comment]
@dbkbali @larry-shyft I'm also experiencing this, I just ran it and do not have the API running

**Comment by dbkbali** [comment]
@GregTheGreek & @larry-shyft this was an error that I was getting earlier - related to govendor which I believe fixed in a subsequent push. Could you make sure you are working with an up to date version of the branch - by performing a git pull. You also may have to ensure that you are not rebuilding from cache by performing the following commands:

```
# stop all containers
docker-compose stop

# remove all containers  - use -f flag if containers still running
docker-compose rm

# remove the $HOME & pg-data directories that contain persistent blockchain & pg data
rm -rf $HOME && rm -rf pg-data

# rebuild all containers fresh
docker-compose up --build

I have repeated this procedure and successfully launched the containers several times on my machine - so I believe your error reflects either a previous cached image or previous version of shyftDockerize

Let me know whether that works!

**Comment by GregTheGreek** [comment]
I'm curious what does rm -rf $HOME do??  because $HOME referneces `/Users/<user>` so would that not delete my user directory?

I ommitted that step and the api exited with the below.

```
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/ethdb
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/common/bitutil
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/edsrzf/mmap-go
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/crypto/bn256/cloudflare
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/golang.org/x/crypto/ripemd160
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/event
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/shyfttracerinterface
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/lib/pq/oid
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/lib/pq
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/ShyftNetwork/go-empyrean/crypto/bn256
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/gorilla/handlers
shyft_block_api_1  | github.com/ShyftNetwork/go-empyrean/shyftBlockExplorerApi/vendor/github.com/gorilla/mux
go-empyrean_shyft_block_api_1 exited with code 2
```

**Comment by dbkbali** [comment]
@GregTheGreek I understand your concerns - the previous instructions should be:

``` cd <project-root> && rm -rf ./$HOME ```

The way GETH  currently operates, it creates a directory in your project root name $HOME - which is used to store the ethash and blockchain data. If you want to start syncing to a new blockchain formed from the genesis block with the designated accounts and the wallet starting.

After investigation, I believe the intent of this configuration set in the config.toml was to have a dynamic storage location of the ethhash - this was configured in this commit https://github.com/ShyftNetwork/go-empyrean/commit/cb959675fcc3ab49df202b24bd239e7936a07b04 by @priom. However toml files cannot use environmental variables for config. I have therefore changed this to store in the user root in a hidden directory called .ethash  [ DatasetDir="~/.ethash" ].

The delete instructions above should be clarified that the directory named $HOME in the project root should be deleted and should be 

``` cd <project-root> && rm -rf ./$HOME ```

With the change of the config.toml I have just pushed the .ethash will be stored in the user root so going forward to remove/reset this data you will need to issue the following command: 

``` rm -rf ~/.ethash ```

NB: For this change you will need to rebuild the shyftgeth service for the new storage location to be captured. If you just would like to rebuild the shyftgeth service you can issue the following command in docker-compose:

```docker-compose up -d --no-deps --build shyftgeth```

If you pull the latest changes - then you shouldnt see a directory named $HOME in the project root.

**Comment by GregTheGreek** [comment]
@dbkbali that makes more sense, give me a few minutes to test this.

**Comment by dbkbali** [comment]
Ok everyone should pull and try with the latest version (@larry-shyft & @GregTheGreek. I had to reconfigure the Block Explorer Service for a bug in Govendor which should now fix the problems you have been having. You may want to rebuild everything from scratch to fix this.

Also note the ethash now saves to the following directory in the project root privatenet/ . To start a fresh private chain you should delete these directories privatenet/ & pg-data/

**Pull request merged**
